[package]
name = "fsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "1.4.1"
walkdir = "2.4.0"
regex = "1.9.1"
once_cell = "1.18.0"
